### PR TITLE
Changed to use JAR file with dependencies

### PR DESCRIPTION
**Pull request by mlgibbons**
Fix to address issue: https://github.com/Azure/draft/issues/748

### CODE REVIEW

**Comment by michelleN** [comment]
cc/ @arun-gupta in case he has anything to add here

**Comment by arun-gupta** [comment]
I suspect this is related to https://github.com/Azure/draft/issues/727. Java pack's Dockerfile tries to search for all the files in a directory and invoke them one by one. I think more intelligence is needed in the Java pack to figure out the exact JAR file that should be invoked instead of a generic `find` command.

**Comment by arun-gupta** [comment]
And the file names may not necessarily be `*-with-dependencies.jar`. For example, WildFly Swarm (now Thorntail) generates the JAR file name as `*-swarm.jar`.

**Comment by squillace** [comment]
I get it. We will have some Java heads look hard at it and circle around here. Thanks for the comments!

**Comment by mlgibbons** [comment]
Hi. There are various ways to address the lack of genericity in the Java buildpack and some discussion is clearly warranted. Fixing the fact that the current pack fails is IMHO a pressing problem as it makes draft look bad for a first time user downloading and trying the Java example; as I did. May I suggest accepting the pull request and I will raise an issue to fix the limitation i.e. "Modified Java buildpack handles only Ubers jars". How does that sounds?

**Comment by michelleN** [comment]
That makes sense @mlgibbons. Thank you for contributing!

Let's continue to track the conversation on how to make this a more generic experience in #727

**Pull request merged**
