### PR TITLE
bump to helm 2.6 compatibility

### PR DESCRIPTION
**Pull request by bacongobbler**
also bumps up for kubernetes 1.7 support

### CODE REVIEW

**Comment by michelleN** [comment]
`make bootstrap` fails on this guy :(

**Comment by bacongobbler** [comment]
This looks a lot like https://github.com/beego/wetalk/issues/32 which appears to indicate it's a RAM issue with our CI system. I'll keep trying to kick off jobs and see if we can free up some RAM on the nodes.

**Comment by bacongobbler** [comment]
punting to v0.8.0 due to CI errors.

**Comment by bacongobbler** [comment]
punting to 0.9; this isn't important to get in for this release... Plus 2.7 with k8s 1.8 compatibility is just around the corner and has some really nice client fixes in helm.

**Comment by bacongobbler** [comment]
closing and rolling this into #380.

**Pull request closed without merging**
