### PR TITLE
Release  v0.0.38

### PR DESCRIPTION
**Pull request by bosesuneha**
# Description

This release fixes the tag versioning issue in the last release.

Fixes # (issue)
Feature # (details)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration. Is it a  breaking change which will impact consuming tool(s).

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by Tatsinnit — APPROVED** [review]
Looks good, thanks.

* Install test seems broke, so might be take a look, please.

**Comment by Tatsinnit** [comment]
Cool, took a quick look. So the release `0.0.37` was broken and no artefacts were polished which has broken install test:

For comparison: https://github.com/Azure/draft/releases

Screenshot 2024-08-14 at 12 57 58 PM

**Review by Tatsinnit — COMMENTED** [review]
Thanks heaps and seems like `0.0.37` manual run had artefacts and all seems good now. 

Minor Question/Observation please: Can you please share the detail of this checksum issue for archival reasons in PR, because from commit history it jsut appear `0.0.37` went out few hours back and then you are change logging this new release. 

Is it commit driven or something else, please? thank you so much. ❤️🙏☕️

**Review by davidgamero — APPROVED** [review]

**Comment by bosesuneha** [comment]
@Tatsinnit Hey , I attempted to fix a bug in the last release by updating the tag to include the bug fix commit. However, I found out this isn't permitted. The reason is the Go [checksum database](https://golang.org/ref/mod#checksum-database) captures a permanent checksum the first time it sees a new module version. This checksum ensures the module remains unchanged from previous downloads, which explains the checksum mismatch error we encountered.

**Pull request merged**
