### PR TITLE
added spring-boot example

### PR DESCRIPTION
**Pull request by jstrachan**
this is a basic spring boot app created via http://start.spring.io/ with web + actuator (which adds health checks)

can be used to demonstrate #476

### CODE REVIEW

**Comment by bacongobbler** [comment]
Thanks @jstrachan! I'll take a look at this one today and see if I can get a PR in to address this.

**Comment by bacongobbler** [comment]
I tested this with #499 and found that it was able to detect java after failing over Shell and Batchfile.

```
><> cd examples/examples-spring-boot
><> draft create
--> Draft detected Shell (47.019482%)
--> Draft could not find a pack for Shell Q_Q
--> Trying the next likeliest language...
--> Draft detected Batchfile (36.304158%)
--> Draft could not find a pack for Batchfile Q_Q
--> Trying the next likeliest language...
--> Draft detected Java (11.260541%)
--> Ready to sail
```

**Comment by bacongobbler** [comment]
@jstrachan would you mind re-naming the example from `examples-*` to `example-*`? That way it follows the same convention as the other example apps (singular vs. plural). Thanks!

**Comment by bacongobbler** [comment]
ping @jstrachan RE the above comment. Once that's done we can merge this in!

**Comment by jstrachan** [comment]
@bacongobbler apologies for the delay - sorted now

**Pull request merged**
