### PR TITLE
draft create creates draft.toml if necessary

### LINKED ISSUE #219: draft create should install draft.toml if chart/ exists
Right now if you have an application that is ready to be deployed by draft but is missing a draft.toml, `draft create` won't provide one.

```
><> draft create
--> chart directory already exists. Ready to sail!
```

This app is not ready to sail because it is missing a draft.toml. Instead, what we should do is

- detect that no pack detection is needed
- drop a draft.toml in the app directory if none already exists

In CLI form, this should look like:

```
><> draft create
!!! chart directory already exists. Skipping pack detection.
--> Ready to sail
```

### PR DESCRIPTION
**Pull request by bnookala**
Fixes #219 by creating `draft.toml` if it has been deleted.

@bacongobbler I wrote a few tests for this, but if it's not comprehensive, let me know. 
In addition, I couldn't figure out a way to generate the testdata samples (ie cmd/draft/testdata/create/**generated**/simple-go-with-chart/draft.toml). Let me know if there's a more straightforward way to do this beyond just committing a file in the right directory

### CODE REVIEW

**Comment by bacongobbler** [comment]
The name convention confused me too, but I don't believe these were autogenerated by the contributor. I haven't found any code that indicates it was either. Your guess is as good as mine :)

**Comment by bnookala** [comment]
@bacongobbler was wondering if there was anything else that needed to be done for this branch?

**Comment by bacongobbler** [comment]
Nothing else needs to be done from my perspective! We will just need to rebase this PR once we've finished merging in all the bigger PRs for v0.6.0 like #237, #239 and #241. After that we can circle back to these smaller (but very nice!) PRs and bring them into the v0.6.0 release.

**Comment by bacongobbler** [comment]
Apologies for letting this one dangle out for so long. Just a large amount of code was being shifted around so we went dark for a while until we could get a clearer picture for v1.0.

**Comment by bacongobbler** [comment]
@bnookala would you mind rebasing this PR? Now that we have CI back up and running, we're planning on doing a v0.6.0 release so it'd be a great feature to have this in the release. Sorry for the long delay!

**Comment by bnookala** [comment]
@bacongobbler will do!

**Comment by bacongobbler** [comment]
hey @bnookala, because this has been sitting for ~7 months I'm going to close this one out, but please re-open if you get the time to rebase this!

**Comment by radu-matei** [comment]
Agreed that it's a good thing - we need to make sure we properly explain what makes a chart suitable for using with Draft (name of the image variable, annotations, labels)

**Pull request closed without merging**
