### PR TITLE
feat(packs): use go-bindata to pack builtin packs

### PR DESCRIPTION
**Pull request by technosophos**
This replaces the hard-coded built-in packs with a generator that uses
go-bindata to read the `packs/` directory and generate an internal
representation that is compiled into the binary.

It adds the make target `generate`, which is called by the build and
cross-compile steps.

Doing things this way has the following advantages:

- Managing built-in packs is much easier (see #95)
- The packed binaries are compressed, so overall memory footprint is
  smaller

The main disadvantage is that it is harder to share files across the
packs. However, it is likely that these paks would diverge over time
anyway.

### CODE REVIEW

**Comment by technosophos** [comment]
@msftclas okay

**Comment by technosophos** [comment]
@bacongobbler I fixed the commit, but the bot does not seem to re-run.

**Comment by bacongobbler** [comment]
Lemme try something...

**Comment by technosophos** [comment]
Okay, given that we all know that at this point the error is with the bot, can we just manually change the label?

**Comment by bacongobbler** [comment]
done. Merge when ready.

**Comment by bacongobbler** [comment]
Would you mind rebasing this when you have the time? I merged #110 which means that this change will need to go into the bindata as well. Sorry!

**Comment by technosophos** [comment]
Rebased with all of the changes to the build packs

**Pull request merged**
