### PR TITLE
uninstall draftd on `draft init`

### LINKED ISSUE #202: figure out upgrade story for draftd
To upgrade draftd in the kubernetes cluster, I run a `helm delete draft --purge` and re-run init.
One option is to fix the `--upgrade` flag on `draft init`
Another option (more temp but maybe slightly better than what we have now) is to push draft to the kubernetes charts repo or its own repo and push updated draft charts there so a user could do a `helm upgrade draft stable/draft` instead of the delete and purge step.

### PR DESCRIPTION
**Pull request by bacongobbler**
This enables users to upgrade the draft daemon on every new release.

closes #202

### CODE REVIEW

**Comment by michelleN** [comment]
How come we're choosing to uninstall instead of upgrading the image? @bacongobbler

**Comment by bacongobbler** [comment]
That might be a better way to handle this. I figured that because we're at a point where we are constantly making breaking changes to Draft we might want to do something a little more destructive until we have a better upgrade story... At least for now.

Perhaps we can move forward with this as a crutch, but keep #202 open until we decide that the upgrade path is fairly stable? For example I'm currently working on a hack to implement #168 which may change how `draft init` works or how the chart is laid out.

**Comment by bacongobbler** [comment]
For what it's worth this was pulled out from #347 so it's completely fine if we don't put this in.

**Comment by michelleN** [comment]
Alright that's cool. I'll lgtm and then we can throw the upgrade flag in or whatever we decided from #202 before 1.0

**Pull request merged**
