### PR TITLE
ref(server): isolate registry auth in file

### PR DESCRIPTION
**Pull request by michelleN**

### CODE REVIEW

**Comment by michelleN** [comment]
@bacongobbler 
There's no new path for that. It's in the same package, so RegistryConfig should be accessible as per usual.

**Comment by michelleN** [comment]
Looking into CI though!!

**Comment by bacongobbler** [comment]
Ah I'm a derp. Ignore me. That was pre-caffeinated me talking. ☕️

**Comment by bacongobbler** [comment]
You'll probably need to call `glide up` as well to get those checked into `glide.lock`

**Comment by bacongobbler** [comment]
Huh that certainly is a very odd error.

```
[0;33m[WARN]	[mUnable to checkout github.com/gogo/protobuf
[0;31m[ERROR]	[mUpdate failed for github.com/gogo/protobuf: Unable to get repository
[0;33m[WARN]	[mUnable to checkout k8s.io/kubernetes
[0;31m[ERROR]	[mUpdate failed for k8s.io/kubernetes: Unable to get repository
[0;33m[WARN]	[mUnable to checkout github.com/docker/docker
[0;31m[ERROR]	[mUpdate failed for github.com/docker/docker: Unable to get repository
[0;31m[ERROR]	[mFailed to install: Unable to get repository
```

The first line is especially important. It's unable to check out an existing clone to the right revision! We've been having docker volume issues with the drives filling up on the slaves. Let me see if I can clear up some disk space on the kubernetes cluster so jobs will run as expected.

**Pull request merged**
