### PR TITLE
Add ACR Build support to Draft

### PR DESCRIPTION
**Pull request by bacongobbler**
https://aka.ms/acr/build

TODO

- [x] add docs

### CODE REVIEW

**Comment by squillace** [comment]
I'm gonna pull and try it out.

**Comment by bacongobbler** [comment]
not yet; gotta rebase this first.

**Comment by squillace** [comment]
_rebase like the wind_

**Comment by bacongobbler** [comment]
This is now working, so I'm removing the WIP label. I'll add tests/docs as others start testing this :)

```
><> draft up
Draft Up Started: 'example-python': 01CBSX7TJXV32E9KFRRD86WR8J
example-python: Building Docker Image: SUCCESS ⚓  (10.0020s)
example-python: Releasing Application: SUCCESS ⚓  (4.8859s)
Inspect the logs with `draft logs 01CBSX7TJXV32E9KFRRD86WR8J`
```

To test, here's my Draft config:

```
><> draft config list
KEY                	VALUE                       
registry           	bacoacrbuildtest2.azurecr.io
resource-group-name	acrbuildtest                
container-builder  	acrbuild
```

You'll need to do the following:

1. build draft from this PR
1. create a resource group in EastUS
1. create a container registry in that resource group, in EastUS as well
1. set up your config similar to mine shown above, substituting the resource group and registry values with your own
1. Call `az login`
1. Run the following to test out an example app:

```
cd examples/example-python
draft create
draft up
```

Occasionally, I'm noticing the following failure on ACR Build's end, so I'll need to follow up with them to figure out the root cause if it's on my end or not:

```
><> draft logs
time="2018-04-23T18:51:47Z" level=info msg="Running command docker login -u 00000000-0000-0000-0000-000000000000 --password-stdin bacoacrbuildtest2.azurecr.io"
Login Succeeded
time="2018-04-23T18:51:47Z" level=info msg="Untarring to /root/acr-builder/src"
time="2018-04-23T18:51:47Z" level=error msg="invalid reference format"
Build ID: eastus2 failed because of an internal error after 1.604753761s
```

**Comment by bacongobbler** [comment]
good point. I'll file a ticket to do so.

**Comment by bacongobbler** [comment]
fixed/rebased on master. @squillace if you feel like taking this for a spin, I'd be happy to take you on a magic carpet ride.

magic carpet ride

**Comment by bacongobbler** [comment]
docs have been added to this PR; let me know if I missed anything.

**Comment by fibonacci1729** [comment]
Pretty straightforward and the code looks good to me.

**Pull request merged**
