### PR TITLE
bump ASP.NET to 2.0

### LINKED ISSUE #325: ASP.NET Core 2
It's been out for a while. You, as Microsoft, should have a starter pack for it out of the box.

### PR DESCRIPTION
**Pull request by bacongobbler**
No replacement for ASP.NET 1.0, but we can eventually come back to that road. For now we should support the latest version of ASP.NET available.

closes #325.

### CODE REVIEW

**Comment by bacongobbler** [comment]
Working and manually tested.

```
><> draft up
Draft Up Started: 'mortal-buffoon'
mortal-buffoon: Building Docker Image: SUCCESS ⚓  (160.2048s)
mortal-buffoon: Pushing Docker Image: SUCCESS ⚓  (16.0084s)
mortal-buffoon: Releasing Application: SUCCESS ⚓  (0.9451s)
mortal-buffoon: Build ID: 01BV7J5T18G8MJZ971M8SEPFF1
><> draft connect
Connecting to your app...SUCCESS...Connect to your app on localhost:56475
Starting log streaming...
      Request finished in 0.2274ms 200
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://172.17.0.12:80/
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 0.0841ms 200
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:56475/
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 0.4508ms 200
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://172.17.0.12:80/
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 0.1819ms 200
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://172.17.0.12:80/
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 0.0944ms 200
```

```
><> curl localhost:56475
Hello World!
```

**Comment by michelleN** [comment]
@bacongobbler let me know when you resolve the conflicts and I'll do a manual test for this one :)

**Comment by bacongobbler** [comment]
I'm going to hold off until #347 has been merged as that one is a little more difficult to rebase.

**Comment by squillace** [comment]
Hey cats, I'm sitting here with @spboyer and he'd like to mow over this PR a bit; can we hold off until he attacks it?

**Comment by bacongobbler** [comment]
Looks like he has. Thanks @spboyer!

**Comment by rspaulino** [comment]
Since draft create isn't working for me yet I copy all the files from the PR and skip the draft create but when I run draft up I get the following error

```
$ draft up
Draft Up Started: 'torrid-hummingbird'
torrid-hummingbird: Building Docker Image: SUCCESS ⚓  (142.9726s)
torrid-hummingbird: Pushing Docker Image: SUCCESS ⚓  (57.0417s)
torrid-hummingbird: Releasing Application: SUCCESS ⚓  (0.3145s)
torrid-hummingbird: Build ID: 01BXCADR9G96NVCPNC8820TXZG

$ draft connect
Connecting to your app...Error: could not find ready pod
```

I'm running version 0.8.0 and create a simple asp.net core 2.0 project. 

is there any documentation for debug? or verbose because since everything is SUCESS I'm wondering at what part is the process breaking. 

FYI: I ran the draft create and up with the example for node and everything work perfect.

**Comment by bacongobbler** [comment]
You can check using `kubectl` to get an idea on the health of your pods. Everything’s deployed in the default namespace unless you changed that parameter in draft.toml.

**Comment by bacongobbler** [comment]
It’ll normally take some time for the pods to initially come up, FYI.

**Comment by squillace** [comment]
also, let's get draft create working for you.

**Comment by rspaulino** [comment]
@bacongobbler sorry it was my mistake first time user here and since I hand copy all the files from the PR to my computer I make the mistake, I guess the Chart.yaml name:csharp must have a directory name csharp inside chart now it's working.

@squillace I try but since I'm using asp.net core 2 it didn't recognize or create the files I'm running version 0.8.0 I think support for .net 2.0 coming on version 0.9.0

**Comment by squillace** [comment]
the draft pack at https://github.com/squillace/draft-packs has one for F# using the dotnetcore2 with giraffe framework. I'll see about getting an aspnetcore2 one working. You can create your OWN draft pack for it right now until .9 has a basic one. :-) I'll help!

**Comment by bacongobbler** [comment]
Done!

**Pull request merged**
