### PR TITLE
Add .NET Core support

### PR DESCRIPTION
**Pull request by alexpilotti**
Includes a .NET Core Starter Pack and an example

### CODE REVIEW

**Comment by bacongobbler** [comment]
23,000 LOC?! Can't we commit a much smaller example app? This seems a bit excessive for a hello world app.

**Comment by alexpilotti** [comment]
That's the very basic sample generated with "dotnet new mvc ..." as by readme.txt. I'm going to replace it with a smaller one :)

**Comment by alexpilotti** [comment]
@bacongobbler I replaced the sample. LOC count dropped significantly. :)

**Comment by bacongobbler** [comment]
this looks much better, thank you.

You'll also need to do 2 things:

1. call `make generate` to autogenerate the pack files
2. fix up the unit tests to show 7 packs instead of 6

Once that's done, I'd be happy to merge.

**Comment by alexpilotti** [comment]
@bacongobbler done, I put the autogenerated file change in a separate commit

**Comment by bacongobbler** [comment]
thank you so much! :)

**Pull request merged**
