### PR TITLE
[WIP] Add initial --container/-c flag for connect

### PR DESCRIPTION
**Pull request by radu-matei**
cc @michelleN

### CODE REVIEW

**Comment by radu-matei** [comment]
So choosing which container to connect to works right now - what should be the default behaviour with multiple containers? Connect to the first one, or create tunnel to all containers (container ports) in the pod? (In this case where should the logs come from?)

**Comment by radu-matei** [comment]
I would also tackle #429 here. Thoughts?

**Comment by radu-matei** [comment]
Any ideas here?
Thanks!

**Comment by michelleN** [comment]
Hey @radu-matei - Sorry for the delay! We were at a team offsite last week. 

Thanks so much for your contribution here. I'll review and test this shortly. I believe the default behavior should be to create a tunnel to all containers. This will help folks debug sidecar containers better!

**Comment by radu-matei** [comment]
Ok - then where should the logs come from?
Right now, the logs come from the container you connect to.

**Comment by radu-matei** [comment]
Closing in favor of #528, which removes old and not useful commits.

**Pull request closed without merging**
