### PR TITLE
feat(packs): use go-bindata to pack builtin packs

### PR DESCRIPTION
**Pull request by technosophos**
This replaces the hard-coded built-in packs with a generator that uses
go-bindata to read the `packs/` directory and generate an internal
representation that is compiled into the binary.

It adds the make target `generate`, which is called by the build and
cross-compile steps.

Doing things this way has the following advantages:

- Managing built-in packs is much easier (see #95)
- The packed binaries are compressed, so overall memory footprint is
  smaller

The main disadvantage is that it is harder to share files across the
packs. However, it is likely that these paks would diverge over time
anyway.

### CODE REVIEW

**Comment by errordeveloper** [comment]
> The main disadvantage is that it is harder to share files across the
packs. However, it is likely that these paks would diverge over time
anyway.

I agree, and I'm sure we can accommodate for some way of sharing common subsets of files.

**Comment by bacongobbler** [comment]
This is a fantastic change. Really happy to see this as the first "big" PR after coming back from a 2-week vacation!

**Comment by bacongobbler** [comment]
Would you mind taking a look at your commit though? Seems like your email address may not be a Microsoft one which is tripping up the CLA bot. Thanks!

**Comment by technosophos** [comment]
Looks like I might have to close and re-open this PR to change the committer.

**Pull request closed without merging**
