### PR TITLE
Adding some clarifications about the requirements of the application.

### PR DESCRIPTION
**Pull request by TopherGopher**
Problem Statement:
I attempted to use draft on a personal project and ran into several roadblocks that led me down a hole trying to debug. Had I just had this paragraph, I would have saved hours of debug time (since I believed the error was in my app).

Adding a small chunk of text clarifying the requirements for a Python application.

Ideally, it would be great for the help text to dynamically print depending on the application since the error messages were a little mystic, but that's down the line.

### CODE REVIEW

**Comment by bacongobbler** [comment]
this looks good. :) we can eventually remove sections of this documentation once we have smarter detection in place for the default python pack in https://github.com/Azure/draft/issues/352. Thank you for the PR!

**Comment by bacongobbler** [comment]
Would it be possible to throw this in a different document though? I would prefer to keep the scope of the getting started guide to *just* the example python application. Perhaps another document called "Further Reading" or something, which would describe next steps after the basic getting started guide?

**Comment by TopherGopher** [comment]
I mean, I'm still really new with this project, but I kept looking for a document that was Python specific and Go specific. Really, at the end of the day, I wanted a troubleshooting doc ultimately.
But if you give me the fnames, I can move this wherever.

**Comment by bacongobbler** [comment]
We don't have any language-specific documentation, but I think that would be the right way to go forward with this PR :)

**Pull request closed without merging**
